name: Deploy to AWS

on: [release, workflow_dispatch]

jobs:
  deploy:
    name: Deploy to development
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - run: npm install -g aws-cdk
      - run: npm install
      - run: npm --prefix ./lambda/ses-password-lambda install --production=true
      - run: npm run build
      - run: >-
          wget https://github.com/aws/aws-sam-cli/releases/download/sam-cli-beta-cdk/aws-sam-cli-linux-x86_64.zip -P /tmp/
          && unzip /tmp/aws-sam-cli-linux-x86_64.zip -d /tmp/sam-installation
          && sudo /tmp/sam-installation/install
      - run: sam-beta-cdk build
      - run: cdk deploy -a .aws-sam/build --require-approval=never
